### PR TITLE
Example of bundling deps using webpack

### PR DESCRIPTION
**Pull request by spalladino**
Work in progress! There are two samples, one in js and another in ts.

- The sample in ts works, but it bundles all dependencies (including those flagged as external in webpack) which is a no-go for autotasks (we cannot have the user copy-paste a snippet 40k lines long).
- The sample in js runs, but does nothing (does not log anything to stdout). Which is odd, because it's the same code as the ts sample.

### CODE REVIEW

**Comment by frangio** [comment]
I think one of the issues is that defining

```
  externals: {
    'defender-relay-client': 'defender-relay-client',
  }
```

will only match `import 'defender-relay-client';` and not `import 'defender-relay-client/lib/relayer';`.

It's possible to use [a function](https://webpack.js.org/configuration/externals/#function) to match the latter as well.

**Comment by frangio** [comment]
I put together an example using Rollup which I find much easier to configure. https://github.com/OpenZeppelin/defender-autotask-examples/pull/4

The output bundle also looks infinitely simpler.

**Comment by frangio** [comment]
As for why the JavaScript example isn't running, it seems like the `handler` function is not exported from the bundle. The reason it works in the TypeScript example is that you configured it with `"module": "commonjs"` and that causes tsc itself to emit an `exports.handler = handler;` statement.

How do autotasks behave if there is no `handler` function exported? Is it considered an error?

**Comment by spalladino** [comment]
> How do autotasks behave if there is no handler function exported? Is it considered an error?

Indeed. They expect an exported handler function to be present.

**Comment by spalladino** [comment]
I've added the function for managing `defender-relay-client` as an external, and the bundle is down to a manageable size, but now I'm hitting another issue: `dotenv` is meant to be used only locally (so I defined it as external, so it's not bundled). However, in the output bundle, webpack eagerly loads it, which fails since it's not available. Any idea on how to tell webpack **not** to eager load modules that are originally dynamically required? Even better, any idea on how to tell webpack not to generate the `__webpack_module_cache__` and `__webpack_require__`, and just use the native one?

As for the js example, I added `libraryTarget: commonjs` to the output, to see if that did the trick - but didn't work either.

**Comment by frangio** [comment]
I don't know if it's possible to configure those things. :confused:

**Comment by spalladino** [comment]
> I don't know if it's possible to configure those things. confused

Got it. I'll leave this PR open in case someone wants to take this on, or we have more time to allocate here. In the meantime, the example with rollup you built is perfect for this use case.

**Comment by spalladino** [comment]
Replaced by https://github.com/OpenZeppelin/defender-autotask-examples/pull/7

**Pull request closed without merging**
